routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*Assessment*/
Route::resource('assessments', 'AssessmentController');

/*Tasks*/
Route::resource('tasks', 'TaskController');

/* Users */
Route::resource('users', 'UserController');
Route::get('myprofile', 'UserController@myProfile')->name('myprofile');

/* Projects */
Route::resource('projects', 'ProjectController');

/* Trello */
Route::resource('trello', 'TrelloController');

/*GitHub*/
Route::resource('github', 'GitHubController');

app/Project.php
<?php

namespace App;
use Carbon\Carbon;
use App\User;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $primaryKey = 'id';

    protected $fillable = [
        'title',
        'type',
        'user_id',
        'description',
        'status',
        'github',
        'trello',
        'token_board_trello',
        'token_repository_github',
        'assessment_id',
        'start_date',
        'end_date',
    ];

    public function userSender()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public static function getDateAttribute($value)
    {
        if($value == null){
            return "Indefinido";
        }
        else{
            return Carbon::parse($value)->format('d/m/Y');
        }
    }

    public static function getType($value)
    {
        $values = ['Interno', 'Externo'];
        return $values[$value];
    }

    public static function getStatus($value)
    {
        $values = ['No Prazo', 'Sem Término Estimado', 'Risco', 'Atrasado', 'Parado', 'Finalizado'];
        return $values[$value];
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\Assessment;
use App\User;
use GuzzleHttp\Client;

class ProjectController extends Controller
{
    protected $request;
    private $repository;

    public function __construct(Request $request, Project $project)
    {
        $this->middleware('auth');
        $this->request = $request;
        $this->repository = $project;
    }

    public function index()
    {
        $projects = Project::get();
        /*$projects = Project::where('user_id', Auth()->user()->id)->get();*/
        return view('app.projects.index', compact('projects'));
    }

    public function create()
    {
        if(Auth()->user()->token_trello === null)
        {
        $trelloData = [];
        $gitHubData = [];
        }
        else{
        $client = new Client();
        $key = env('TRELLO_KEY');

        $token_trello = Auth()->user()->token_trello;
        $token_github = Auth()->user()->token_github;

        $api_trello = 'https://api.trello.com/1/members/me/boards?key=' . $key . '&token=' . $token_trello;
        $response_trello = $client->get($api_trello);

        $api_gitHub = 'https://api.github.com/users/'. $token_github .'/repos';
        $response_gitHub = $client->get($api_gitHub);


        if ($response_trello->getStatusCode() == 200) {
            $json = $response_trello->getBody();
            $trelloData = json_decode($json);
        }

        if ($response_gitHub->getStatusCode() == 200) {
            $json = $response_gitHub->getBody();
            $gitHubData = json_decode($json);
        }
    }
        return view ('app.projects.create', ['trelloData' => $trelloData, 'gitHubData' => $gitHubData ] );

    }

    public function store(Request $request)
    {
        $project = new Project();
         $project = $project->create([
         'title'  => $request['title'],
         'type'  => $request['type'],
         'user_id'  => $request['user_id'],
         'description'  => $request['description'],
         'status'  => $request['status'],
         'token_repository_github' => $request['token_repository_github'],
         'token_board_trello' => $request['token_board_trello'],
         'start_date'  => $request['start_date'],
         'end_date'  => $request['end_date'],
     ]);

        \Session::flash('success','Projeto cadastrado com sucesso!');

        return redirect()->route('projects.index');
    }

    public function show($id)
    {
        if(Auth()->user()->token_trello === null)
        {
        $trelloData = [];
        $gitHubData = [];
        }
        else{
        $users = User::get();
        $projects = Project::findOrFail($id);
        $assessments = Assessment::where('projects_id', $id)->get();
        $client = new Client();
        $cURL_Tokrn = env('CURL_TOKEN');


        $token_board = $projects->token_board_trello;
        $repo_gitHub = $projects->token_repository_github;

        $api_trello = 'https://api.trello.com/1/boards/' . $token_board . '/cards';
        $response_trello = $client->get($api_trello);

        $api_gitHub = 'https://api.github.com/repos/'. $repo_gitHub .'/commits';
        $response_gitHub = $client->get($api_gitHub);

        $api_gitHub_brach = 'https://api.github.com/repos/'. $repo_gitHub .'/branches';
        $response_gitHub_brach = $client->get($api_gitHub_brach);

        $api_gitHub_issue = 'https://api.github.com/repos/'. $repo_gitHub .'/issues';
        $response_gitHub_issue = $client->get($api_gitHub_issue);

        if (!$project = $this->repository->find($id));

        if ($response_trello->getStatusCode() == 200) {
            $json = $response_trello->getBody();
            $trelloBoard = json_decode($json);
        }

        if ($response_gitHub->getStatusCode() == 200) {
            $json = $response_gitHub->getBody();
            $gitHubRepository = json_decode($json);
        }


        if ($response_gitHub_brach->getStatusCode() == 200) {
            $json = $response_gitHub_brach->getBody();
            $gitHubBranch = json_decode($json);
        }

        if ($response_gitHub_issue->getStatusCode() == 200) {
            $json = $response_gitHub_issue->getBody();
            $gitHubIssue = json_decode($json);
        }
    }
        return view('app.projects.show')->with(['project' => $project, 'assessments' => $assessments,  'users' => $users, 'trelloBoard' => $trelloBoard, 'gitHubRepository' => $gitHubRepository, 'gitHubBranch' => $gitHubBranch, 'gitHubIssue' => $gitHubIssue]);
    }

    public function edit($id)
    {
        $gitHubData = [];
        $trelloData = [];
        $client = new Client();
        $key = env('TRELLO_KEY');

        $token_trello = Auth()->user()->token_trello;
        $token_github = Auth()->user()->token_github;

        $api_trello = 'https://api.trello.com/1/members/me/boards?key=' . $key . '&token=' . $token_trello;
        $response_trello = $client->get($api_trello);

        $api_gitHub = 'https://api.github.com/users/'. $token_github .'/repos';
        $response_gitHub = $client->get($api_gitHub);

        if ($response_trello->getStatusCode() == 200) {
            $json = $response_trello->getBody();
            $trelloData = json_decode($json);
        }

        if ($response_gitHub->getStatusCode() == 200) {
            $json = $response_gitHub->getBody();
            $gitHubData = json_decode($json);
        }

        $project = Project::findOrFail($id);
        return view('app.projects.edit', ['project' => $project,'trelloData' => $trelloData, 'gitHubData' => $gitHubData ]);
    }

    public function update(Request $request, $id)
    {
        $project = Project::findOrFail($id);
        $project->update([
            'title'  => $request['title'],
            'type'  => $request['type'],
            'description'  => $request['description'],
            'status'  => $request['status'],
            'token_repository_github' => $request['token_repository_github'],
            'token_board_trello' => $request['token_board_trello'],
            'start_date'  => $request['start_date'],
            'end_date'  => $request['end_date'],
        ]);

        \Session::flash('success','Projeto atualizado com sucesso!');

        return redirect()->route('projects.index');
    }

    public function destroy($id)
    {
        $project = Project::findOrFail($id);
        $project->delete();

        \Session::flash('success','Projeto deletado com sucesso!');

        return redirect()->route('projects.index');
    }
}

resources/views/app/projects/partials/assessments.blade.php
@foreach ($assessments as $assessment )
@if($assessment->type == 0)
<div class="card card-purple">
    <div class="card-header">
        <h3 class="card-title"><i class="far fa-thumbs-up"></i> {{ $assessment->title }} - Impacto {{ \App\Util::getPoint($assessment->type) }} </h3>
    </div>
@else
<div class="card card-pink">
    <div class="card-header">
        <h3 class="card-title"><i class="far fa-thumbs-down"></i> {{ $assessment->title }} - Impacto {{ \App\Util::getPoint($assessment->type) }} </h3>
    </div>
@endif
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <h5 class="body-title"> Problema</h5>
                <p class="paragrafo">{{ $assessment->description }}</p>
                <hr>
                <h5 class="body-title"> Solução</h5>
                <p class="paragrafo">{{ $assessment->resolution }}</p>
            </div>
        </div>
    </div>
</div>
@endforeach

resources/views/app/projects/partials/cards.blade.php
<div class="row d-flex align-items-stretch">
    @foreach ($trelloBoard as $item)
        <div class="col-xs-1 col- col-xs-6 col-md-4 align-items-stretch">
            <blockquote class="trello-card">
                <a href="{{ $item->shortUrl }}">Trello Card</a>
            </blockquote>
        </div>
    @endforeach
</div>


@push('other_js')

<script src="https://p.trellocdn.com/embed.min.js"></script>

@endpush

resources/views/app/projects/partials/detail.blade.php
<div class="row">
    <div class="col-md-4 col-sm-6 col-12">
        <div class="info-box">
            <span class="info-box-icon bg-purple"><i class="far fa-flag"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">Status do Projeto</span>
                <span class="info-box-number">{{ \App\Project::getStatus($project->status) }}</span>
            </div>
        </div>
    </div>

    <div class="col-md-4 col-sm-6 col-12">
        <div class="info-box">
            <span class="info-box-icon bg-info"><i class="far fa-calendar"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">Data início</span>
                <span class="info-box-number">{{ \App\Project::getDateAttribute($project->start_date) }}</span>
            </div>
        </div>
    </div>

    <div class="col-md-4 col-sm-6 col-12">
        <div class="info-box">
            <span class="info-box-icon bg-pink"><i class="far fa-calendar-check"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">Data fim</span>
                <span class="info-box-number">{{ \App\Project::getDateAttribute($project->end_date) }}</span>
            </div>
        </div>
    </div>
</div>

<div class="card card-purple">
    <div class="card-header">
        <h3 class="card-title">
            <i class="far fa-file-alt"></i>
            Descrição
        </h3>
    </div>
    <div class="card-body">
        <p class="description">{{ $project->description }}</p>
    </div>
</div>

resources/views/app/projects/partials/form.blade.php
@csrf
<div class="form-group">
    <input type="hidden" name="user_id" class="form-control" value="{{ Auth()->user()->id ?? old(Auth()->user()->id) }}">
</div>
<div class="form-group">
    <label>Nome do Projeto:</label>
    <input type="text" class="form-control" name="title" placeholder="Nome o Projeto:" value="{{ $project->title ?? old('title') }}">
</div>
<div class="form-group">
    <label>Descrição:</label>
    <input type="text" name="description" class="form-control" placeholder="Descrição:" value="{{ $project->description ?? old('description') }}">
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <label>Tipo:</label>
        <select name="type" class="form-control" placeholder="Tipo:">
            <option {{($project->type ?? old('type'))=="0"? 'selected':''}} value="0">Interno</option>
            <option {{($project->type ?? old('type'))=="1"? 'selected':''}} value="1">Externo</option>
        </select>
    </div>
    <div class="form-group col-md-6">
        <label>Status:</label>
        <select name="status" class="form-control" placeholder="Status:">
            <option {{($project->status ?? old('status'))=="0"? 'selected':''}} value="0">No prazo</option>
            <option {{($project->status ?? old('status'))=="1"? 'selected':''}} value="1">Sem Término Estimado</option>
            <option {{($project->status ?? old('status'))=="2"? 'selected':''}} value="2">Risco</option>
            <option {{($project->status ?? old('status'))=="3"? 'selected':''}} value="3">Atrasado</option>
            <option {{($project->status ?? old('status'))=="4"? 'selected':''}} value="4">Parado</option>
            <option {{($project->status ?? old('status'))=="5"? 'selected':''}} value="5">Finalizado</option>
        </select>
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <label>Quadro Trello</label>
        @if(Auth::user()->token_trello === null || Auth::user()->token_trello == "" || $trelloData == [] )
        <input type="text" class="form-control" placeholder="Vincular conta do Trello para vizualizar os quadros" disabled>
        @else
        <select name="token_board_trello" class="form-control" >
            @foreach($trelloData as $item )
            <option value="{{ $item->id}}">{{ $item->name }}</option>
            @endforeach
        </select>
        @endif
    </div>
    <div class="form-group col-md-6">
        <label>Repositório GitHub:</label>
        @if(Auth::user()->token_github === null || Auth::user()->token_github == "" || $gitHubData == [] )
        <input type="text" class="form-control" placeholder="Vincular conta do GitHub para vizualizar repositórios" disabled>
        @else
        <select name="token_repository_github" class="form-control" >
            @foreach($gitHubData as $item )
            <option value="{{ $item->full_name }}">{{ $item->full_name }}</option>
            @endforeach
        </select>
        @endif
    </div>
</div>
<div class="form-row">
    <div class="form-group col-md-6">
        <label>Data Inicio:</label>
        <input type="date" name="start_date" class="form-control" placeholder="Data Inicio" value="{{ $project->start_date ?? old('start_date') }}">
    </div>
    <div class="form-group col-md-6">
        <label>Data Fim:</label>
        <input type="date" name="end_date" class="form-control" placeholder="Data Fim:" value="{{ $project->end_date ?? old('end_date') }}">
    </div>
</div>
<div class="form-group">
    <button type="submit" class="btn bg-gradient-purple">Enviar</button>
    <a href="{{ route('projects.index') }}"  class="btn bg-gradient-info" >Meus Projetos</a>
</div>

resources/views/app/projects/partials/issues.blade.php
<div class="card card-purple">
    <div class="card-header">
      <h3 class="card-title">
          <i class="fas fa-exclamation"></i>
        Lista de Atividades (Issues - GitHub)
      </h3>
    </div>
    <div class="card-body">
      @foreach ( $gitHubIssue as $issue )
      <div class="card-footer card-comments">
        <div class="card-comment">
          <a class="link-issue" href="{{ $issue->html_url }}" target="_blank">
            {{ $issue->title }}
          </a>
          @foreach ( $issue->labels as $label )
          <span class="badge" style="background-color: #{{ $label->color }}; color: #fff">
            {{ $label->name }}
          </span>
          @endforeach
          <div class="comment-text">
            <span class="text-muted float-right">{{ $issue->updated_at}}</span>
          </div>
          <div class="comment-text">
            <span class="issues">
              Responsável:
              <p>
                {{ $issue->assignee->login }}
                <img class="avatar img-s" src="{{ $issue->assignee->avatar_url }}" alt="User Image"/>
              </p>
              <p>
                {{ $issue->number }} opened {{ $issue->created_at }} by {{ $issue->user->login }}
              </p>
            </span>
          </div>
        </div>
      </div>
      @endforeach
    </div>
  </div>

resources/views/app/projects/partials/reposit.blade.php
<div class="card-body table-responsive">
    <div class="card card-purple">
      <div class="card-header">
        <h3 class="card-title">
          <i class="fas fa-code-branch"></i>
          Funcionalidades em (Branchs)
        </h3>
      </div>
      <div class="card-body">
        <div class="row">
          @foreach ($gitHubBranch as $branch)
          <div class="col-md-4">
            <p><a href="https://github.com/{{ $project->token_repository_github }}/tree/{{ $branch->name }}" target="_blank"><i class="fas fa-code-branch"></i> {{ $branch->name }}</a></p>
          </div>
          @endforeach
        </div>
      </div>
    </div>

    <div class="card card-purple">
      <div class="card-header">
        <h3 class="card-title">
          <svg
            class="octicon octicon-git-commit"
            viewBox="0 0 16 18"
            version="1.1"
            width="16"
            height="18"
            aria-hidden="true"
            fill="#fff"
          >
            <path
              fill-rule="evenodd"
              d="M10.86 7c-.45-1.72-2-3-3.86-3-1.86 0-3.41 1.28-3.86 3H0v2h3.14c.45 1.72 2 3 3.86 3 1.86 0 3.41-1.28 3.86-3H14V7h-3.14zM7 10.2c-1.22 0-2.2-.98-2.2-2.2 0-1.22.98-2.2 2.2-2.2 1.22 0 2.2.98 2.2 2.2 0 1.22-.98 2.2-2.2 2.2z"
            ></path>
          </svg>

          Atualizações no Repositório (Commits)
        </h3>
      </div>
      <div class="card-body">
        <table id="tabela" class="table table-borderless">
          <thead>
            <tr>
              <th>Mensagem</th>
              <th>Autor</th>
              <th>Data</th>
              <th>Mudanças</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($gitHubRepository as $item )
            <tr>
              <td><a href="{{ $item->html_url }}" target="_blank">{{ \App\Util::maxMsgCommit($item->commit->message) }}</a></td>
              <td>{{ $item->commit->author->name }}</td>
              <td>{{ $item->commit->committer->date }}</td>
              <td>
                <a href="{{ $item->html_url }}" target="_blank"><button type="submit" class="btn bg-gradient-secondary">
                    {{ \App\Util::shaGitHub($item->sha) }}
                  </button></a>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>

resources/views/app/projects/partials/settings.blade.php
<form action="{{ route('projects.destroy', $project->id) }}" method="post">
    @csrf
    @method('DELETE')
    <a class="btn bg-gradient-info" href="{{ route('projects.edit', $project->id) }}"><i class="fas fa-edit"></i>Editar</button></a>
    <button type="submit" class="btn bg-gradient-pink"><i class="fas fa-trash-alt"></i> Remover Projeto</button>
</form>

resources/views/app/projects/partials/team.blade.php
<div class="row align-items-stretch">
    @foreach ( $users as $item)
    <div class="col-12 col-sm-6 col-md-4 align-items-stretch">
      <div class="card bg-light">
        <div class="card-header text-muted border-bottom-0">
          {{ $item->position }}
        </div>
        <div class="card-body pt-0">
          <div class="row">
            <div class="col-7">
              <h2 class="lead"><b>{{ $item->name }}</b></h2>
              <ul class="ml-4 mb-0 fa-ul text-muted">
                <li class="small"><span class="fa-li"><i class="fas fa-at"></i></span> Email: {{ $item->email }}</li>
              </ul>
            </div>
            <div class="col-5 text-center pt-0">
                <img class="img-circle img-fluid" src="../../../../../../assets/img/avatar.png" alt="{{ $item->name }}">
            </div>
          </div>
        </div>
        <div class="card-footer">
          <div class="text-right">
            <a href="{{ route('users.show', $item->id) }}" target="_blank"><button type="submit" class="btn bg-gradient-info btn-sm"><i class="fas fa-user"></i>Ver Perfil</button></a>
          </div>
        </div>
      </div>
    </div>
    @endforeach
  </div>