routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*Assessment*/
Route::resource('assessments', 'AssessmentController');

/*Tasks*/
Route::resource('tasks', 'TaskController');

/* Users */
Route::resource('users', 'UserController');
Route::get('myprofile', 'UserController@myProfile')->name('myprofile');

/* Projects */
Route::resource('projects', 'ProjectController');

/* Trello */
Route::resource('trello', 'TrelloController');

/*GitHub*/
Route::resource('github', 'GitHubController');

app/Project.php
<?php

namespace App;
use Carbon\Carbon;
use App\User;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $primaryKey = 'id';

    protected $fillable = [
        'title',
        'type',
        'user_id',
        'description',
        'status',
        'github',
        'trello',
        'token_board_trello',
        'token_repository_github',
        'assessment_id',
        'start_date',
        'end_date',
    ];

    public function userSender()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public static function getDateAttribute($value)
    {
        if($value == null){
            return "Indefinido";
        }
        else{
            return Carbon::parse($value)->format('d/m/Y');
        }
    }

    public static function getType($value)
    {
        $values = ['Interno', 'Externo'];
        return $values[$value];
    }

    public static function getStatus($value)
    {
        $values = ['No Prazo', 'Sem Término Estimado', 'Risco', 'Atrasado', 'Parado', 'Finalizado'];
        return $values[$value];
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Project;
use App\Assessment;
use App\User;
use GuzzleHttp\Client;

class ProjectController extends Controller
{
    protected $request;
    private $repository;

    public function __construct(Request $request, Project $project)
    {
        $this->middleware('auth');
        $this->request = $request;
        $this->repository = $project;
    }

    public function index()
    {
        $projects = Project::get();
        /*$projects = Project::where('user_id', Auth()->user()->id)->get();*/
        return view('app.projects.index', compact('projects'));
    }

    public function create()
    {
        if(Auth()->user()->token_trello === null)
        {
        $trelloData = [];
        $gitHubData = [];
        }
        else{
        $client = new Client();
        $key = env('TRELLO_KEY');

        $token_trello = Auth()->user()->token_trello;
        $token_github = Auth()->user()->token_github;

        $api_trello = 'https://api.trello.com/1/members/me/boards?key=' . $key . '&token=' . $token_trello;
        $response_trello = $client->get($api_trello);

        $api_gitHub = 'https://api.github.com/users/'. $token_github .'/repos';
        $response_gitHub = $client->get($api_gitHub);


        if ($response_trello->getStatusCode() == 200) {
            $json = $response_trello->getBody();
            $trelloData = json_decode($json);
        }

        if ($response_gitHub->getStatusCode() == 200) {
            $json = $response_gitHub->getBody();
            $gitHubData = json_decode($json);
        }
    }
        return view ('app.projects.create', ['trelloData' => $trelloData, 'gitHubData' => $gitHubData ] );

    }

    public function store(Request $request)
    {
        $project = new Project();
         $project = $project->create([
         'title'  => $request['title'],
         'type'  => $request['type'],
         'user_id'  => $request['user_id'],
         'description'  => $request['description'],
         'status'  => $request['status'],
         'token_repository_github' => $request['token_repository_github'],
         'token_board_trello' => $request['token_board_trello'],
         'start_date'  => $request['start_date'],
         'end_date'  => $request['end_date'],
     ]);

        \Session::flash('success','Projeto cadastrado com sucesso!');

        return redirect()->route('projects.index');
    }

    public function show($id)
    {
        if(Auth()->user()->token_trello === null)
        {
        $trelloData = [];
        $gitHubData = [];
        }
        else{
        $users = User::get();
        $projects = Project::findOrFail($id);
        $assessments = Assessment::where('projects_id', $id)->get();
        $client = new Client();
        $cURL_Tokrn = env('CURL_TOKEN');


        $token_board = $projects->token_board_trello;
        $repo_gitHub = $projects->token_repository_github;

        $api_trello = 'https://api.trello.com/1/boards/' . $token_board . '/cards';
        $response_trello = $client->get($api_trello);

        $api_gitHub = 'https://api.github.com/repos/'. $repo_gitHub .'/commits';
        $response_gitHub = $client->get($api_gitHub);

        $api_gitHub_brach = 'https://api.github.com/repos/'. $repo_gitHub .'/branches';
        $response_gitHub_brach = $client->get($api_gitHub_brach);

        $api_gitHub_issue = 'https://api.github.com/repos/'. $repo_gitHub .'/issues';
        $response_gitHub_issue = $client->get($api_gitHub_issue);

        if (!$project = $this->repository->find($id));

        if ($response_trello->getStatusCode() == 200) {
            $json = $response_trello->getBody();
            $trelloBoard = json_decode($json);
        }

        if ($response_gitHub->getStatusCode() == 200) {
            $json = $response_gitHub->getBody();
            $gitHubRepository = json_decode($json);
        }


        if ($response_gitHub_brach->getStatusCode() == 200) {
            $json = $response_gitHub_brach->getBody();
            $gitHubBranch = json_decode($json);
        }

        if ($response_gitHub_issue->getStatusCode() == 200) {
            $json = $response_gitHub_issue->getBody();
            $gitHubIssue = json_decode($json);
        }
    }
        return view('app.projects.show')->with(['project' => $project, 'assessments' => $assessments,  'users' => $users, 'trelloBoard' => $trelloBoard, 'gitHubRepository' => $gitHubRepository, 'gitHubBranch' => $gitHubBranch, 'gitHubIssue' => $gitHubIssue]);
    }

    public function edit($id)
    {
        $gitHubData = [];
        $trelloData = [];
        $client = new Client();
        $key = env('TRELLO_KEY');

        $token_trello = Auth()->user()->token_trello;
        $token_github = Auth()->user()->token_github;

        $api_trello = 'https://api.trello.com/1/members/me/boards?key=' . $key . '&token=' . $token_trello;
        $response_trello = $client->get($api_trello);

        $api_gitHub = 'https://api.github.com/users/'. $token_github .'/repos';
        $response_gitHub = $client->get($api_gitHub);

        if ($response_trello->getStatusCode() == 200) {
            $json = $response_trello->getBody();
            $trelloData = json_decode($json);
        }

        if ($response_gitHub->getStatusCode() == 200) {
            $json = $response_gitHub->getBody();
            $gitHubData = json_decode($json);
        }

        $project = Project::findOrFail($id);
        return view('app.projects.edit', ['project' => $project,'trelloData' => $trelloData, 'gitHubData' => $gitHubData ]);
    }

    public function update(Request $request, $id)
    {
        $project = Project::findOrFail($id);
        $project->update([
            'title'  => $request['title'],
            'type'  => $request['type'],
            'description'  => $request['description'],
            'status'  => $request['status'],
            'token_repository_github' => $request['token_repository_github'],
            'token_board_trello' => $request['token_board_trello'],
            'start_date'  => $request['start_date'],
            'end_date'  => $request['end_date'],
        ]);

        \Session::flash('success','Projeto atualizado com sucesso!');

        return redirect()->route('projects.index');
    }

    public function destroy($id)
    {
        $project = Project::findOrFail($id);
        $project->delete();

        \Session::flash('success','Projeto deletado com sucesso!');

        return redirect()->route('projects.index');
    }
}

resources/views/app/projects/create.blade.php
@extends('adminlte::page')

@section('content_header')
<h1>Cadastrar Projeto</h1>
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('projects.store') }}" method="post" enctype="multipart/form-data" class="form">
                        @include('app.projects.partials.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/projects/edit.blade.php
@extends('adminlte::page')

@section('content_header')
<h1>Editar Projeto</h1>
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('projects.update', $project->id) }}" method="post" enctype="multipart/form-data" class="form">
                        @method('PUT')
                        @include('app.projects.partials.form')
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/projects/index.blade.php
@extends('adminlte::page')

@section('content_header')

<h1>Projetos</h1>

@endsection

@section('content')

<div class="container-fluid">
    @include('includes.alerts')
    <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Meus Projetos</h3>
              <div class="card-tools">
                <div class="input-group input-group-sm">
                    <a href="{{ route('projects.create') }}"><button type="submit" class="btn bg-gradient-purple"><i class="fas fa-plus"></i> Novo</button></a>
                </div>
              </div>
            </div>
            <div class="card-body table-responsive">
              <table id="tabela" class="table table-bordered">
                <thead>
                  <tr>
                    <th>Projeto</th>
                    <th>Lider</th>
                    <th>Descrição</th>
                    <th>Tipo</th>
                    <th>Status</th>
                    <th>Data início</th>
                    <th>Data fim</th>
                    <th>Ação</th>
                  </tr>
                </thead>
                <tbody>
                @foreach ($projects as $project )
                <tr>
                    <td> <a href="{{ route('projects.show', $project->id) }}">{{ $project->title }}</a></td>
                    <td>{{ $project->userSender->name }}</td>
                    <td>{{ \App\Util::limitCharacters( $project->description) }}</td>
                    <td>{{ \App\Project::getType($project->type) }}</td>
                    <td>{{ \App\Project::getStatus($project->status) }}</td>
                    <td>{{ \App\Project::getDateAttribute($project->start_date) }}</td>
                    <td>{{ \App\Project::getDateAttribute($project->end_date) }}</td>
                    <td class="center-btn">
                        @if(Auth::user()->id == $project->user_id)
                        <table class="table-borderless table-sm">
                            <tr>
                                <td>
                                    <a href="{{ route('projects.edit', $project->id) }}"><button type="submit" class="btn bg-gradient-purple btn-sm margin-btn"><i class="fas fa-edit"></i></button></a>
                                </td>
                                <td>
                                    <a href="{{ route('projects.show', $project->id) }}"><button type="submit" class="btn bg-gradient-info btn-sm margin-btn"><i class="far fa-eye"></i></button></a>
                                </td>
                                <td>
                                    <form action="{{ route('projects.destroy', $project->id) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn bg-gradient-pink btn-sm margin-btn"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                </td>
                            </tr>
                        </table>
                        @else
                        <table class="table-borderless table-sm">
                            <tr>
                                <td>
                                    <a href="{{ route('projects.show', $project->id) }}"><button type="submit" class="btn bg-gradient-info btn-sm margin-btn"><i class="far fa-eye"></i></button></a>
                                </td>
                            </tr>
                        </table>
                        @endif
                    </td>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
  </div>
@endsection

@push('other_js')

<script>
    $(document).ready(function () {
		var table = $('#tabela').DataTable({
			iDisplayLength: 10,
			language: {
				url: "//cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json",
				select: {
					rows: {
						_: '%d itens selecionados',
						0: 'Nenhum item selecionado',
						1: '1 item selecionado'
					}
				}
			}
		});
    });
</script>

@endpush

resources/views/app/projects/show.blade.php
@extends('adminlte::page')

@section('content_header')
<h1>{{ $project->title }}</h1>

    <style>
        .nav-pills .nav-link.active, .nav-pills .show > .nav-link {
            color: #fff;
            background-color: #6f42c1;
        }
        .description{
            text-align: justify;
        }
        .avatar{
            display: inline-block;
            overflow: hidden;
            line-height: 1;
            vertical-align: middle;
            border-radius: 3px;
            max-width: 30px;
        }
        .link-issue{
            color: black
        }
        .paragrafo{
            padding-left: 20px;
        }
        .body-title{
            font-size: 1.10em;
        }
    </style>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-pills">
                        <li class="nav-item"><a class="nav-link active" href="#sobre" data-toggle="tab"><i class="far fa-clipboard"></i> Sobre</a></li>
                        <li class="nav-item"><a class="nav-link" href="#time" data-toggle="tab"><i class="fas fa-users"></i> Time</a></li>
                        <li class="nav-item"><a class="nav-link" href="#trello" data-toggle="tab"><i class="fab fa-trello"></i> Trello</a></li>
                        <li class="nav-item"><a class="nav-link" href="#github" data-toggle="tab"><i class="fab fa-github"></i> GitHub</a></li>
                        <li class="nav-item"><a class="nav-link" href="#relatorio" data-toggle="tab"><i class="far fa-file-alt"></i> Relatório</a></li>
                        <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab"><i class="fas fa-cog"></i> Configurações</a></li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="sobre">
                            @include('app.projects.partials.detail')

                            @include('app.projects.partials.issues')
                        </div>

                        <div class="tab-pane" id="time">
                            @include('app.projects.partials.team')
                        </div>

                        <div class="tab-pane" id="trello">
                            @include('app.projects.partials.cards')
                        </div>

                        <div class="tab-pane" id="github">
                            @include('app.projects.partials.reposit')
                        </div>

                        <div class="tab-pane" id="relatorio">
                            @include('app.projects.partials.assessments')
                        </div>

                        <div class="tab-pane" id="settings">
                            @include('app.projects.partials.settings')
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('other_js')



@endpush