routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*Assessment*/
Route::resource('assessments', 'AssessmentController');

/*Tasks*/
Route::resource('tasks', 'TaskController');

/* Users */
Route::resource('users', 'UserController');
Route::get('myprofile', 'UserController@myProfile')->name('myprofile');

/* Projects */
Route::resource('projects', 'ProjectController');

/* Trello */
Route::resource('trello', 'TrelloController');

/*GitHub*/
Route::resource('github', 'GitHubController');

app/Assessment.php
<?php

namespace App;
use App\Project;

use Illuminate\Database\Eloquent\Model;

class Assessment extends Model
{
    protected $primaryKey = 'id';

    protected $fillable = [
        'projects_id',
        'title',
        'description',
        'resolution',
        'type',

    ];

    public function projectSender()
    {
        return $this->belongsTo(Project::class, 'projects_id');
    }
}

app/Http/Controllers/AssessmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Assessment;
use App\Project;

class AssessmentController extends Controller
{
    protected $request;
    private $repository;

    public function __construct(Request $request, Assessment $assessment)
    {
        $this->middleware('auth');
        $this->request = $request;
        $this->repository = $assessment;
    }

    public function index()
    {
        $assessments = Assessment::get();
        return view('app.assessments.index', compact('assessments'));
    }

    public function create()
    {
        $projects = Project::get();
        return view ('app.assessments.create', ['projects' => $projects]);
    }

    public function store(Request $request)
    {
        $assessment = new Assessment();
        $assessment = $assessment->create([
            'projects_id' => $request['projects_id'],
            'title' => $request['title'],
            'description' => $request['description'],
            'resolution' => $request['resolution'],
            'type' => $request['type']
     ]);

        \Session::flash('success','Relatório cadastrado com sucesso!');

        return redirect()->route('assessments.index');
    }

    public function show($id)
    {
        if (!$assessment = $this->repository->find($id))
        return redirect()->back();
        return view('app.assessments.show', ['assessment' => $assessment]);
    }

    public function edit($id)
    {
        $projects = Project::get();
        $assessment = Assessment::findOrFail($id);
        return view('app.assessments.edit', ['assessment' => $assessment, 'projects' => $projects]);

    }

    public function update(Request $request, $id)
    {
        $assessment = Assessment::findOrFail($id);
        $assessment->update([
            'projects_id' => $request['projects_id'],
            'title' => $request['title'],
            'description' => $request['description'],
            'resolution' => $request['resolution'],
            'type' => $request['type']
        ]);

        \Session::flash('success','Relatório atualizado com sucesso!');
        return redirect()->route('assessments.index');
    }

    public function destroy($id)
    {
        $assessment = Assessment::findOrFail($id);
        $assessment->delete();

        \Session::flash('success','Relatório deletado com sucesso!');

        return redirect()->route('assessments.index');
    }
}

resources/views/app/assessments/create.blade.php
@extends('adminlte::page')

@section('content_header')
<h1>Cadastrar Relatório</h1>
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('assessments.store') }}" method="post" enctype="multipart/form-data" class="form">
                        @include('app.assessments.partials.form')
                        <button type="submit" class="btn bg-gradient-indigo">Enviar</button>
                            <a href="{{ route('assessments.index') }}"  class="btn bg-gradient-info" >Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/assessments/edit.blade.php
@extends('adminlte::page')

@section('content_header')

<h1>Editar Relatório</h1>

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('assessments.update', $assessment->id) }}" method="post" enctype="multipart/form-data" class="form">
                        @method('PUT')
                        @include('app.assessments.partials.form')
                        <div class="form-group">
                            <button type="submit" class="btn bg-gradient-purple">Enviar</button>
                            <a href="{{ route('assessments.index') }}"  class="btn bg-gradient-info" >Voltar</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/app/assessments/index.blade.php
@extends('adminlte::page')

@section('content_header')

<h1>Relatórios</h1>

@endsection

@section('content')

<div class="container-fluid">
    @include('includes.alerts')
    <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Lições aprendidas</h3>
              <div class="card-tools">
                <div class="input-group input-group-sm">
                    <a href="{{ route('assessments.create') }}"><button type="submit" class="btn bg-gradient-purple"><i class="fas fa-plus"></i> Novo</button></a>
                </div>
              </div>
            </div>
            <div class="card-body table-responsive">
              <table id="tabela" class="table table-bordered">
                <thead>
                  <tr>
                    <th>Projeto</th>
                    <th>Título</th>
                    <th>Descrição</th>
                    <th>Resultado</th>
                    <th>Ponto</th>
                    <th>Ações</th>
                  </tr>
                </thead>
                <tbody>
                @foreach ($assessments as $assessment )
                  <tr>
                    <td><a href="{{ route('projects.show', $assessment->projects_id) }}">{{ $assessment->projectSender->title}}</a></td>
                    <td>{{ $assessment->title }}</td>
                    <td>{{ \App\Util::limitCharacters($assessment->description) }}</td>
                    <td>{{ \App\Util::limitCharacters($assessment->resolution) }}</td>
                    <td>{{ \App\Util::getPoint($assessment->type) }}</td>
                    <td>
                        <table class="table-borderless table-sm">
                            <tr>
                                <td>
                                    <a href="{{ route('assessments.edit', $assessment->id) }}"><button type="submit" class="btn bg-gradient-purple btn-sm"><i class="fas fa-edit"></i></button></a>
                                </td>
                                <td>
                                    <a href="{{ route('assessments.show', $assessment->id) }}"><button type="submit" class="btn bg-gradient-info btn-sm"><i class="far fa-eye"></i></button></a>
                                </td>
                                <td>
                                    <form action="{{ route('assessments.destroy', $assessment->id) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn bg-gradient-pink btn-sm"><i class="fas fa-trash-alt"></i> </button>
                                        </form>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
  </div>
@endsection

@push('other_js')

<script>
    $(document).ready(function () {
		var table = $('#tabela').DataTable({
			iDisplayLength: 10,
			language: {
				url: "//cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json",
				select: {
					rows: {
						_: '%d itens selecionados',
						0: 'Nenhum item selecionado',
						1: '1 item selecionado'
					}
				}
			}
		});
    });
</script>
@endpush